//created on: Nov 1, 2018
package Rules

//list any import classes here.
import com.model.*;
import com.enums.*;


//declare any global variables here
rule "test" salience 4
   when
   	ad:AutoData(category == DriverCategory.B1)
   then
   	ad.setExprience(40);
   	System.out.println("Modification created.");
   end

rule "test2" salience 3
    when
        c:Customer(email == null)
    then
        c.setBeneficiary(true);
        System.out.println("Customer modified through services");
    end